language: conda
conda:
- 4.12.0

install:
- pip install -r requirements.txt

before_script:
- source prepare-conda-env.sh

script:
- pytest i-tests/tutorial_example_1.py
- pytest i-tests/tutorial_example_2.py
- pytest i-tests/tutorial_example_3.py
- pytest i-tests/task_1.py
- pytest i-tests/task_2.py
- pytest i-tests/task_4.py